version: 0.0
os: linux
files:
  - source: target/mad_library.jar
    destination: /opt/webapps/
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
  ValidateService:
    - location: scripts/verify_service.sh
      runas: root
